export const DEFAULT_STUDENT = {
	id: '',
	first_name: '',
	last_name: '',
	picture: '',
	gender: '',
	birthdate: '',
	nationality: '',
	role: {
		name: '',
	},
	contact: {
		email: '',
		phone: '',
		linkedin: '',
		instagram: '',
	},
	started_at: '',
	finished_at: '',
	graduated_at: '',
	created_at: '',
	updated_at: '',
	deleted_at: '',
}

export const students = [
	{
		id: '',
		slug: 'erik-giorgis',
		first_name: 'Erik',
		last_name: 'Giorgis',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2022/03/Goldwyn-Kontaktparty-2022-0157-e1647535029228.jpg',
		gender: 'MALE',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'President',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'bassem-alsakhawy',
		first_name: 'Bassem',
		last_name: 'Alsakhawy',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2022/10/Bassem_Alsakhawy-scaled-e1667155633481.jpg',
		gender: 'MALE',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'VP & Externals',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'francesco-kruk',
		first_name: 'Francesco',
		last_name: 'Kruk',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2022/10/kruk-francesco.jpg.jpg',
		gender: 'MALE',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'Treasurer',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'alexandre-mazaud',
		first_name: 'Alexandre',
		last_name: 'Mazaud',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2022/10/unnamed-scaled.jpg',
		gender: 'MALE',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'External Relations',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'nora-tommila',
		first_name: 'Nora',
		last_name: 'Tommila',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2022/10/20221011_AmivContact_IzedinFotografie_622-scaled-e1667155930389.jpg',
		gender: 'FEMALE',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'External Relations',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'tjardo-symens',
		first_name: 'Tjardo',
		last_name: 'Symens',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2022/10/Avimed-bbq-30-1-von-1-01-01-scaled-e1667155821973.jpeg',
		gender: 'MALE',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'External Relations',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'ishita-shreevastava',
		first_name: 'Ishita',
		last_name: 'Shreevastava',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2022/10/WhatsApp-Image-2022-10-26-at-7.41.34-PM-e1667156193704.jpeg',
		gender: 'FEMALE',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'PR & Externals',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'cedric-gmur',
		first_name: 'Cedric',
		last_name: 'Gmür',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2021/11/cedric.jpg',
		gender: 'MALE',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'Academic Politics',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'umberto-procchio',
		first_name: 'Umberto',
		last_name: 'Procchio',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2021/11/umberto-e1638227263798.jpeg',
		gender: '',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'Internal Relations',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'li-zeng',
		first_name: 'Li',
		last_name: 'Zeng',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2022/10/70837927-45d3-4c99-b41a-7b46f8d341d0-e1667157124205.jpg',
		gender: '',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'Partner Relations',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'tiara-greber',
		first_name: 'Tiara',
		last_name: 'Greber',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2022/10/FullSizeRender.jpg',
		gender: '',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'Digital Marketing',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'dimitrios-barmperis',
		first_name: 'Dimitrios',
		last_name: 'Barmperis',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2022/10/Barmperis-Dimitrios-e1667158425369.jpg',
		gender: '',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'Digital Marketing',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'palash-bagdy',
		first_name: 'Palash',
		last_name: 'Bagdy',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2021/11/Inked_DSA0826_LIw-e1637606440500.jpg',
		gender: '',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'Event Manager',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'lara-hohn',
		first_name: 'Lara',
		last_name: 'Höhn',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2022/03/WhatsApp-Image-2022-03-17-at-18.00.44.jpeg',
		gender: '',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'Event Manager',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'samuel-luther',
		first_name: 'Samuel',
		last_name: 'Luther',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2022/10/IMG_0986-e1667156396443.jpg',
		gender: '',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'Event Manager',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
	{
		id: '',
		slug: 'nerit-kunesko',
		first_name: 'Nerit',
		last_name: 'Künesko',
		picture:
			'https://www.obis.ethz.ch/wp-content/uploads/2022/10/Nerit_Foto.jpeg',
		gender: '',
		birthdate: '',
		nationality: '',
		roles: [
			{
				started_at: '2022-09-01',
				ended_at: '',
				name: 'Event Manager',
			},
		],
		contact: {
			email: '',
			phone: '',
			linkedin: '',
			instagram: '',
		},
		started_at: '',
		finished_at: '',
		created_at: '',
		updated_at: '',
		deleted_at: '',
	},
]
